### ISSUE TITLE
Catch would compile much faster if the 'main' was only compiled once

### ISSUE THREAD

**Issue by TBBle** [cyber-dojo/start-points-languages#5]
I've been playing with gpp_catch, and it's quite slow to build the tests.

Catch has a feature that you can compile a lot of the slow-to-build things and once-used things into a different file, and only that file needs `CATCH_CONFIG_MAIN` defined.

This is easy-enough to do by creating a main.cpp when you start a session, but it makes sense to me to deliver it already-set up.

----

Does it make sense to have a main.cpp that isn't visible to the user? It's not clear from http://blog.cyber-dojo.org/2016/08/cyber-dojo-start-points-manifestjson.html whether non-visible files are actually copied over or not, and how (or if) the system would handle conflicts with user-created files.

----

Another option is something in the Makefile like this:
````make

# This rule builds the Catch main() loop once, rather than in each test run
.main.o: /usr/include/catch.hpp
	@echo '#include "catch.hpp"' | $(CXX) -x c++ $(CXXFLAGS) -DCATCH_CONFIG_MAIN -c -o $@ -
````
and having `test` depend on `.main.o`.

I have cyber-dojo.sh checking for a .main.cpp to go with the above:
````sh
[ -f .main.cpp ] && echo ".main.cpp conflicts with the build system" && exit 1
make
````

----
Both of these of course assume taking away the default `--always-make` parameter in cyber-dojo.sh. Is there a particular reason to use that?

**Comment by JonJagger** [comment]
Hi Paul,
the reason is simply that I am not an expert in Catch (or make) and did the simplest possible thing that worked. At the time the runner was stateless so there was no point in doing anything other than --always-make because everything was completely new for each test run anyway. But the runner is now stateful so dropping --always-make sounds excellent. I think the simplest is to not make main.cpp visible to the user and add the rule for it in the makefile as you suggest. 
Awesome
Cheers
Jon

**Comment by TBBle** [comment]
Terrific. Once I'm fully set-up here for playing with Docker and extending cyber-dojo, I'll see about submitting a PR for this.

**Comment by TBBle** [comment]
On the note of having non-visible files, what's the rationale for putting catch.hpp in /usr/include (which necessitates another docker image) rather than just being in the start-point? Is it to make catch.hpp fall under the system-includes collection? Is it considered a good practice in cyber-dojo to make fixed files work that way? Would it make sense for main.cpp to be similarly outside of the start-point file collection, and inside the Catch docker image instead?

**Comment by JonJagger** [comment]
The idea is broadly that visible-files are files you see in the browser and might reasonably edit and are the focus of the practice. In contrast, consider something like Java-JUnit for example which is provided via JAR files. catch.hpp is different of course because its header-based and full of templates. So on balance I feel catch.hpp not being visible is appropriate. Hence it is in /usr/include/. Plus catch.hpp is a BIG header which I don't really want to have to send to the server for every test event. 

However, there is a tension. You could argue cyber-dojo.sh should not be visible for example. However I like the "value-system" of making files visible. If I'm in any doubt I prefer to make a file visible. 

Now I think of it, main.cpp is kind of borderline. It would be small and I can see value in being visible. For example one thing I see people doing sometimes is trying to write their own main() and I think it might help alleviate this. Happy either way.

Also, I'd value any feedback on issues you have doing any dev work. For example, now I think of it, there is a startup script to clone all the cyber-dojo repos, but there is no script to pull all the repos...

**Comment by TBBle** [comment]
I agree with the value of main.cpp being visible. If possible, I'd want it to be down with the makefile and cyber-dojo.sh, to indicate that it's not the focus of interest.

I hadn't thought of the browser-roundtrip concern. That's a good reason to keep large, static files out of the start-point, even if they're "source".

Side-note: It took me ages to work out where catch.hpp was. I assumed it was local but not visible, but make told me I was wrong. I ended up looking at the Dockerfile in the repository to get its location.

**Comment by JonJagger** [comment]
re main.cpp down with the makefile. That could easily be hard-coded (like cyber-dojo.sh and makefile already are). Longer term I think a proper 'lowlight' entry in the start-point manifest is the way to go.
Feel free to email me whenever something is being a speed-bump.
Would anything you can think of have helped re catch.hpp's location?

**Comment by TBBle** [comment]
If it had been explicitly in the Makefile, something like `-isystem /usr/share/catch/`. (Which would also mark it as a system header, suppressing warnings therein).

Also including it with `#include <catch.hpp>` might have flagged it as coming from the system paths, but that's more subtle I think. When I couldn't find it, I did go back to see if that was the case.

**Comment by JonJagger** [comment]
Agreed. I appreciate the feedback. Feel free to make any makefile/src changes you feel appropriate.

**Comment by JonJagger** [comment]
I've now implemented Catch's main in a separate .cpp file and updated the makefile to do an incremental make. Much faster now. 
Cheers
